worker_processes auto;

events {
    worker_connections 1024;
}

http {
    client_max_body_size 50m;

    upstream ocr_backend {
        least_conn;
        server ocr-gpu0:9004;
        server ocr-gpu1:9004;
        server ocr-gpu0b:9004;
        server ocr-gpu1b:9004;
    }

    server {
        listen 9004;

        proxy_read_timeout 120s;
        proxy_send_timeout 120s;

        location / {
            proxy_pass http://ocr_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
